---
title: "One-letter Match"
author: "jmb"
date: "4/16/2021"
output: 
  html_document:
    keep_md: true
---

### Purpose of this file
- To simulate how many instances it takes to match at least one initial (first or last)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

### Load packages
```{r}
library(ggplot2)
library(mosaic)
```

### Import data
```{r}
d <- read.csv('initials.csv', stringsAsFactors = TRUE)
```

### Data processing

First, compute the proportion and percentage distributions for both the first and last initials.

```{r}
# Create new dataframe of just the alphabet
d.l = data.frame('Letter' = as.factor(letters))
# Create new dataframe of the proportion distribution of the first initial and last initial
l1.prop <- data.frame(prop.table(table(d$first)))
l2.prop <- data.frame(prop.table(table(d$last)))
# Rename the columns
names(l1.prop) <- c('Letter', 'First_Proportion')
names(l2.prop) <- c('Letter', 'Last_Proportion')
# Add the first-letter proportions onto the dataframe of Letters
d.l <- merge(d.l, l1.prop, by = c('Letter'), all.x = TRUE)
# Add the last-letter proportions onto the dataframe of Letters
d.l <- merge(d.l, l2.prop, by = c('Letter'), all.x = TRUE)
# For letters that have never been played, place a '0' as the proportion
d.l$First_Proportion <- ifelse(is.na(d.l$First_Proportion) == TRUE, 0, d.l$First_Proportion)
d.l$Last_Proportion  <- ifelse(is.na(d.l$Last_Proportion) == TRUE, 0, d.l$Last_Proportion)
# For ease, add a Percentage variable for each letter
d.l$First_Percentage <- d.l$First_Proportion*100
d.l$Last_Percentage  <- d.l$Last_Proportion*100
```

### Simulation

```{r}

# Function that outputs the total number of weeks before one of the radio initials match the one of the guessed initials in the correct order.

  OneLetter <- function(){  
    # Time-to-event for matching both initials
    i <- 0
    match <- 'lose'
    while(match == 'lose'){
      # Add a week for each run of the loop
      i <- i + 1
      
      # Select the initials for the game
      game1  <- sample(d.l$Letter, size = 1, prob = d.l$First_Proportion)
      game2  <- sample(d.l$Letter, size = 1, prob = d.l$Last_Proportion)
      # Select the initials for the guess
      guess1 <- sample(d.l$Letter, size = 1, prob = d.l$First_Proportion)
      guess2 <- sample(d.l$Letter, size = 1, prob = d.l$Last_Proportion)
      
      # Create conditional for win or not, using OR logic
      if(guess1 == game1 | guess2 == game2){
        match <- 'win'
      }else{}
    }
    print(i)
  }
```

### Rum simulation 5000 times and collect results

```{r echo = TRUE, results = 'hide'}
# Set a seed number to reproduce results (number taken from random.org)
set.seed(366896971)
  d1 <- do(5000)*OneLetter()
```
  
### Percentile calculation

```{r}

## Last time one match occurred: Game 334 (i.e., Week = 0 for 334)
## As of 4/17/2021, on Game 354 or 20 weeks

  # Probability of being longer than the given number of weeks
  count(d1$OneLetter > 20) / nrow(d1)  
  count(d1$OneLetter > 21) / nrow(d1)  
```

### Plot!
  
```{r}
  ggplot(data = d1, aes(x = OneLetter)) +
    geom_histogram(binwidth = 1, aes(y = ..density..), color = 'plum', fill = 'plum') +
    geom_vline(xintercept = 20, lty = 'dashed') +
    ylab('Probability Density') +
    annotate('text', x = 32, y = 0.05, label = paste0(100*count(d1$OneLetter > 20) / nrow(d1),'% chance for 20 or more weeks'), color = 'blue') +
    scale_x_continuous(breaks = c(seq(from = 0, to = max(d1$OneLetter), by = 2)), name = 'Weeks Between One-letter Matches') +
    theme_light() +
    theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank())

```